# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=9.2.2
group=top.theillusivec4.curios
java_version=21

# Curios Specific Info
minecraft_version=1.21.1
mod_name=Curios API
mod_author=C4
mod_id=curios
license=LGPL-3.0-or-later
description=A flexible and expandable accessory/equipment API for users and developers.

# CCLayer Specific

archives_base_name=accessories_cclayer
maven_group=io.wispforest

cc_layer_mod_id=cclayer
cc_layer_mod_name=Curios Compatibility Layer
cc_layer_version=beta.21
cc_layer_mod_author=Blodhgarm
cc_layer_description=Adds Compatibility layer between Curios Based Mods and Accessories API.
cc_layer_credits=Special thanks to C4 for the creation of Curios

issues_url=https://github.com/wisp-forest/accessories/issues
sources_url=https://github.com/wisp-forest/accessories

minecraft_version_range=[1.21, 1.22)
minecraft_version_range_alt=~1.21

accessories_version_range=[1.1.0-beta.24,)

# NeoForge
neoforge_version=21.1.62
neoforge_version_range=[21.1.60,)

# Libs

accessories_version=1.1.0-beta.24+1.21.1
owo_neo_version=0.12.15-beta.9+1.21

# Compatibility
jei_version=19.3.1.24
emi_version=1.1.19+1.21.1
rei_version=16.0.788

# Publishing
cf_id=309927
cf_page=https://www.curseforge.com/minecraft/mc-mods/curios
modrinth_id=vvuO3ImH
modrinth_page=https://modrinth.com/mod/curios
release_type=release
release_versions=1.21.1,1.21
changelog_link=https://github.com/TheIllusiveC4/Curios/blob/1.21.1/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/195/772/636881112930494939.png

# Gradle
org.gradle.jvmargs=-Xmx3G -Dmixin.debug.countInjections=true
org.gradle.daemon=false

parchment_minecraft=1.21
parchment_version=2024.11.10

neo_form_version=1.21.1-20240808.144430

moddevgradle_version=2.0.42-beta